sonar.projectKey=tp-calculator-sonar
sonar.projectName=tp-calculator-sonar
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

# on va compiler vers build/classes dans le workflow
sonar.java.binaries=build/classes
